### ISSUE TITLE
Wrong association of NB(t) with publication Stcherbatsky 1918

### ISSUE THREAD

**Issue by kellner** [ea-east/east-biblio#11]
https://east.ikga.oeaw.ac.at/buddh/ind/7/179/: Stcherbatsky's 1918 edition of NB and NBṬ is marked as a full edition of the Tibetan translation, but this is incorrect because it only contains the Sanskrit text. Also, the bibliographical data is wrong; it lists as publisher "Gerold" (?). Correct: publication place =  Petrograd, publisher = "Izd. Akademii Nauk" (cross-check this with SUEBS).

**Comment by paddymcall** [comment]
This should correspond to SUEBS entry 7.4.T2, which is Stcherbatsky's 1904 edition of the NB and its ṭīkā, in Tibetan.  I.e., the relation is right, but the date, place, and publisher are wrong in EAST's bibliography.  A scan is here: https://archive.org/details/nyayabind00dhar/

**Comment by JamieCreek** [comment]
https://east.ikga.oeaw.ac.at/buddh/ind/7/23/716/ 
I guess this entry (east:5508) has the same problem. The publisher (listed again as "Gerold") and place of publication should be Petrograd 1922, Pamyatmiki indiskoi filosofii 1. This should correspond to SUEBS 7.8.r1.

**Comment by paddymcall** [comment]
The entries got mixed together: Stcherbatsky 1904 (correct title) and Stcherbatsky 1918, corresponding to 7.4.S2. Please add the latter to the bibliography, @JamieCreek.

**Comment by paddymcall** [comment]
Closed with issue #13.
