### ISSUE TITLE
Add Vinītadeva’s Hetubinduṭīkā to EAST

### ISSUE THREAD

**Issue by paddymcall** [ea-east/east-biblio#15]
Peking 5733 is missing. This text corresponds to SUEBS 11.3.T1.
gtan tshigs kyi thigs pa'i rgya cher 'grel: snar thang 3725 she 116a-205b; sde dge 4234 we 100b3-181a7; co ne we 104a1-188b6; {Peking} 5733 ze 1-26b8.

_Originally posted by @JamieCreek in https://github.com/ea-east/east-biblio/issues/5#issuecomment-617700738_

   1) [x] Add to bibliography
   2) [x] Add Vinītadeva’s Hetubinduṭīkā to EAST

**Comment by pchiou6932** [comment]
Done, see: https://east.ikga.oeaw.ac.at/buddh/ind/11/234/
