### ISSUE TITLE
Add Nyāyabindupūrvapakṣasaṅkṣipta to EAST

### ISSUE THREAD

**Issue by paddymcall** [ea-east/east-biblio#16]
Peking 5731 is missing. This text corresponds to SUEBS 17.2.T1.
rigs pa'i thigs pa'i phyogs snga ma mdor bsdus pa: snar thang 3723 zhe 106b-115a; sde dge 4232 we 92a1-99a5; co ne we 95a1–103a1; {Peking} 5731 zhe 113a1-122b6.

1) [x] Add to bibliography
2) [x] Add Kamalaśīla’s Nyāyabindupūrvapakṣasaṅkṣipta to EAST
3) [x] Add “Tosaki, Hiromasa. 1984. ‘Kamalaśīla’s
      Nyāyabindupūrvapakṣesaṃskṣipta.’ In Acta Indologica (Vol VI -
      Mysticism), 477–93. Naritasan Shinshoji.” as a Tibetan edition
      and modern Japanese translation.

_Originally posted by @JamieCreek in https://github.com/ea-east/east-biblio/issues/5#issuecomment-617695132_

**Comment by pchiou6932** [comment]
1. I've created the pages for this work (https://east.ikga.oeaw.ac.at/buddh/ind/17/232/#) and its Tibetan translation (https://east.ikga.oeaw.ac.at/buddh/ind/17/233/) but haven't made the connection.
2.  Sanjit Kumar Sadhukhan has published a reconstructed Sanskrit edition based on the Tibetan together with a English translation (https://www.worldcat.org/title/acarya-kamalasilas-nyayabindu-purvapaksa-samksipta-the-prima-facie-arguments-the-nyayabindu-in-a-nutshell/oclc/289070926?referer=tag_list_view). The IKGA library does not seem to have an exemplar. Does anyone have a pdf? I'll need it for the bibliography.

**Comment by JamieCreek** [comment]
I've created a new EAST entry for this work. The entry in SUEBS (17.2.T1) also contains "lhan kar Kat. (Lalou 700, 701 [vgl. Frauwallner, Buddha. Texte S.98], Yoshimura 694, 695)." Where and how should I include this in the new EAST entry for this work in jabref? Unfortunately, I don't have a pdf copy of the edition you mentioned, Peilin.

**Comment by pchiou6932** [comment]
@JamieCreek : Thanks for creating this entry. The information concerning lhan kar catalog should be added directly on the EAST. I'll (@pchiou6932) do it once the entry has been merged. 
@paddymcall : The page for the Tibetan translation has been connected to that for the Sanskrit text. However, on the page for the Sanskrit, there's no link to the Tibetan. How could I create the link?

**Comment by paddymcall** [comment]
It should be here: https://east.ikga.oeaw.ac.at/buddh/ind/17/232/  Please be sure to reload the page (fully), your browser might be caching things.
