### ISSUE TITLE
EAST Website double entry issues: Pramāṇavārttika

### ISSUE THREAD

**Issue by kellner** [ea-east/east-biblio#23]
This is strictly speaking not about the bibliography, but about database linking, but since we have no other bug reporting system at the moment, I thought I could post this here (please remove if inapprorpriate). 

https://east.ikga.oeaw.ac.at/buddh/ind/7/16/

Two entries appear twice here in different sections: (1) Saccone, "Il Buddha come fonte di retta conoscenza" under Discussions -> English and Discussions -> Other (I suppose it should only be in "other" as it's in Italian), (2) Pecchia 2015 appears twice under Discussions -> English.

**Comment by pchiou6932** [comment]
Thanks for raising the issue. I have removed Saccone's publication from the category 'Discussions -> English'. As for the two entries for Pecchia 2015, they are now merged into one, by moving the note in one entry to another as the two entries originally contain two different notes.
