### ISSUE TITLE
Add text-publication-links for papers in Moriyama 2020 (WSTB 97).

### ISSUE THREAD

**Issue by kellner** [ea-east/east-biblio#24]
All papers in Moriyama 2020 (WSTB 97) have been added to EAST via the Django interface. Text-publication links remain to be added.

**Comment by pchiou6932** [comment]
Bibliographic entries for papers in Moriyama 2020 have been created in east-biblio and linked to related texts (done in Feb. 2021). But since EAST does not include Upāyahṛdaya und Tarkaśastra, Ono's paper on the two works is not linked to EAST.

**Comment by kellner** [comment]
*Tarkaśāstra and *Upāyahṛdaya/Prayogasāra were contained in Steinkellner/Much 1995 in "Appendix A: Werke vor Dignāga", as "Anonyme Vāda-Handbücher". The texts as such should also be contained in EAST. I cannot reconstruct at the moment why they are not there. But I propose that they should be added, just like the other materials from the Appendices (Vasubandhu's Vāda treatises as well as Jaina commentaries on Buddhist pramāṇa literature); we then need to also add relevant literature and update research. For Up./Pra, there is recent work by Katsura and Gillon.

**Comment by kellner** [comment]
Has this been undertaken yet?

**Comment by kellner** [comment]
Please update on the status so that we can close the issue in time.

**Comment by pchiou6932** [comment]
Pages for the works listed in Steinkellner&Much 1995 in Appendix A (Werke vor Dignāga) and Appendix B (Jaina-Werke) are created. So I close this issue.
