### ISSUE TITLE
Small mistake in Frauwallner 1934

### ISSUE THREAD

**Issue by kellner** [ea-east/east-biblio#30]
https://east.ikga.oeaw.ac.at/buddh/ind/7/21/355/

Journal should be "Wiener Zeitschrift für die Kunde des Morgenlandes".

**Comment by kellner** [comment]
(Also, the publication is marked as a partial edition and partial modern translation of SP-t and SPV-t, but it is in fact a complete edition and also a complete modern translation. Please correct.)

**Comment by pchiou6932** [comment]
Thanks for the report. The mistake has been corrected.

**Comment by kellner** [comment]
Then I close the issue.
